### ISSUE TITLE
"Does not work or provide any functionality upon installation" - Google

### ISSUE THREAD

**Issue by TheoBr** [TheoBr/Chrometana#37]
I assumed this was one of the nearly infinite phishing emails I get when I received it. Any clever hacks to make our functionality a little more, uh, "apparent" would be appreciated. 

[Gmail - Action Required_ Chrometana - Redirect Bing Somewhere Better Requires Changes to Comply with Chrome Web Store Policy.pdf](https://github.com/TheoBr/Chrometana/files/1278690/Gmail.-.Action.Required_.Chrometana.-.Redirect.Bing.Somewhere.Better.Requires.Changes.to.Comply.with.Chrome.Web.Store.Policy.pdf)

**Comment by Modelmat** [comment]
Maybe also add like make any search engine go TO YOUR choice?
ie. something searches in Yahoo on a site, this auto makes it go to DuckDuckGo or something

**Comment by BristolITDave** [comment]
Perhaps change the default behaviour to redirect all bing searches to Google? That would fit in with the brief description "Redirect Bing Somewhere Better". Still leave the option to untick this/change this in the options. This way it "does what it says on the tin", while still giving users choice. You may want to just display the additional settings page by default instead of clicking to expand it.

@Modelmat 's suggestion of adding more redirects isn't a bad option either.

**Comment by TheoBr** [comment]
https://github.com/TheoBr/Chrometana/pull/38

**Comment by TheoBr** [comment]
Just shipped the update, we're now in "pending review"

**Comment by TheoBr** [comment]
It shipped (awhile ago)
